export const GLOSSARY = {
  'attention': 'A mechanism that lets each token look at every other token and decide how much weight to give each one. The core idea behind transformers.',
  'multi-head attention': 'Multiple attention operations running in parallel, each learning different types of relationships between tokens.',
  'feedforward': 'A small two-layer network applied to each token independently after attention. It holds a large share of the model capacity.',
  'layernorm': 'Layer Normalization — rescales activations after each sublayer to keep values in a healthy range. Prevents training instability.',
  'rmsnorm': 'Root Mean Square Normalization — a simpler and faster alternative to Layer Normalization. Only scales values, without centering them.',
  'residual': 'A skip connection that adds the input directly to the output of a sublayer. Lets gradients flow back easily during training.',
  'softmax': 'Converts raw attention scores into probabilities that sum to 1. Determines how much each token attends to each other.',
  'embedding': 'A learned lookup table that converts each token ID (an integer) into a dense vector of floating-point numbers.',
  'positional encoding': 'Information added to token embeddings telling the model where each token sits in the sequence.',
  'rope': 'Rotary Position Embedding — encodes position by rotating query and key vectors. Generalizes well to long sequences.',
  'swiglu': 'A feedforward activation variant using two gating paths multiplied together. Common in modern LLMs.',
  'flops': 'Floating Point Operations — a measure of compute cost. More FLOPs means slower and more expensive to run.',
  'tensor': 'A multidimensional array. The core data structure in neural networks.',
  'tensor contract': 'The formal specification of what input and output tensor shapes a component requires. Violating this causes a runtime crash.',
  'invariant': 'A constraint that must always hold throughout the model. Violating it typically causes wrong outputs or a crash.',
  'manifest': 'The locked architecture specification that Yukti extracts from the paper. It is the single source of truth for the schema.',
  'schema': 'The structured representation of the paper\'s architecture — components, shapes, equations, and invariants locked at extraction time.',
}
